name: tiled
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame:
      path: ../..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/tiles/map.tmx
    - assets/images/map-level1.png