version: 2
updates: 
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /doc/_sphinx
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /doc/flame/examples
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /doc/tutorials/klondike/app
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /doc/tutorials/platformer/app
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /doc/tutorials/space_shooter/app
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /examples/games/padracing
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /examples/games/rogue_shooter
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /examples/games/trex
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /examples
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_audio/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_audio
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_bloc/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_bloc
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_fire_atlas/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_fire_atlas
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_forge2d/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_forge2d
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_isolate/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_isolate
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_jenny/jenny
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_jenny
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_lint
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_lottie/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_lottie
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_markdown/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_markdown
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_network_assets/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_network_assets
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_noise
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_oxygen/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_oxygen
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_rive/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_rive
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_riverpod/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_riverpod
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_spine/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_spine
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_splash_screen/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_splash_screen
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_studio
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_svg/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_svg
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_test/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_test
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_tiled/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_tiled
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
