version: 2
updates: 
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /doc/_sphinx
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /doc/flame/examples
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /doc/tutorials/klondike/app
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /doc/tutorials/platformer/app
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /doc/tutorials/space_shooter/app
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /examples/games/padracing
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /examples/games/rogue_shooter
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /examples/games/trex
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /examples
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_jenny
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/flame_studio
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
