name: flame
description: A minimalist Flutter game engine
version: 0.8.4
author: Luan Nico <luannico27@gmail.com>
homepage: https://github.com/luanpotter/flame

flutter:
  uses-material-design: false

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.4.1
  path_provider: ^0.4.0
  box2d: ^0.4.0

dev_dependencies:
  test: ^0.12.34

environment:
  sdk: ">=1.13.0 <2.0.0"
