name: flame
description: A minimalist Flutter game engine
version: 0.9.2
author: Luan Nico <luannico27@gmail.com>
homepage: https://github.com/luanpotter/flame

flutter:
  uses-material-design: false

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.7.5
  ordered_set: ^1.1.1
  path_provider: ^0.4.1
  box2d_flame: ^0.4.2
  synchronized: ^1.5.1+1

dev_dependencies:
  test: ^1.3.0

environment:
  sdk: ">=2.0.0-dev.50.0 <3.0.0"
