name: doc_flame_examples
description: Documentation examples
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flame: ^1.8.1
  flame_rive: ^1.9.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.0.0

flutter:
  assets:
    - assets/
    - assets/images/