name: flame_rive
description: Rive support for the Flame game engine. This uses the rive package and provides wrappers and components to be used inside Flame.
homepage: https://github.com/flame-engine/flame
version: 1.7.2
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flame: ^1.7.4
  flutter:
    sdk: flutter
  rive: ^0.10.4

dev_dependencies:
  dartdoc: ^6.2.2
  flame_lint: ^0.2.0+3
  flame_test: ^1.11.0
  flutter_test:
    sdk: flutter
